### ISSUE TITLE
Where to go from here :)

### ISSUE THREAD

**Issue by zeffii** [metrasynth/sunvox-dll-python#1]
this is super interesting, i'm able to help with some functionality of this! 

am reading this now: http://nbviewer.jupyter.org/gist/gldnspud/38b5d2a94d524f9c743a69de210501e3

**Comment by zeffii** [comment]
no win64 support?

**Comment by matthewryanscott** [comment]
@zeffii, unfortunately there is no 64-bit Windows version of the SunVox DLL just yet. That is up to NightRadio; once one is available we'll definitely support it in the Python wrapper. 😃 

For now you could try to install and use a 32-bit Python 3.5 on Windows. I'd love to know if that works because I don't have a way right now to easily test on Windows on a regular basis.

See also http://stackoverflow.com/a/11642165/72560

**Comment by zeffii** [comment]
a dedicated w32 python/anaconda install it is then... :/    no ETA.

**Comment by zeffii** [comment]
regarding the scripting interface for adding modules / connecting / setting params,  I wrote a small interface for a different program (Buzz -> BLOK)  https://github.com/zeffii/pyBLOK/issues/4  , I certainly would like to continue use some of that shorthand like `>` to connect two modules.

**Comment by matthewryanscott** [comment]
I love the general idea. I'd like to be careful to make sure we don't interfere with `<` and `>`, but there are alternatives like `<<` and `>>` that should work.

Also, I think there's room for handling these shorthands in a consistent way for both the real-time interaction with the API (which is handled by this repo),  as well as the file format (which is handled by radiant-voices).

To that end, I've created these new issues to track the progress of those ideas:
- https://github.com/metrasynth/sunvox-dll-python/issues/2
- https://github.com/metrasynth/radiant-voices/issues/6

Also, since we're using issues here now, I've added some more for radiant-voices that reflect what is on my immediate to-do list:
- https://github.com/metrasynth/radiant-voices/issues/2
- https://github.com/metrasynth/radiant-voices/issues/3
- https://github.com/metrasynth/radiant-voices/issues/4
- https://github.com/metrasynth/radiant-voices/issues/5

I'm going to go ahead and close this ticket in favor of more specific ones. If you'd like to continue having a general chat let's hop on the http://warmcommunity.space/ slack in the `#sunvox-dll` channel, and/or the forums. I keep an eye on both. 👀 😃

**Comment by zeffii** [comment]
cool, looking forward to it.
